const boot=window.AEACUS_BOOTSTRAP;
const apiHeaders={'Content-Type':'application/json','X-Aeacus-Token':boot.token};
let project=null, issues=[], targetDir='', saveTimer=null, evaluationByIndex={};
const $=(q,root=document)=>root.querySelector(q), $$=(q,root=document)=>[...root.querySelectorAll(q)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeHtml(value){const documentValue=new DOMParser().parseFromString(value||'','text/html');documentValue.querySelectorAll('script,iframe,object,embed,style').forEach(node=>node.remove());documentValue.querySelectorAll('*').forEach(node=>[...node.attributes].forEach(attribute=>{if(attribute.name.toLowerCase().startsWith('on')||(['href','src'].includes(attribute.name.toLowerCase())&&attribute.value.trim().toLowerCase().startsWith('javascript:')))node.removeAttribute(attribute.name)}));return documentValue.body.innerHTML}
const conditionTypes=['FileContains','FileContainsNot','FileContainsRegex','FileContainsRegexNot','FileEquals','FileEqualsNot','PathExists','PathExistsNot','DirContains','DirContainsNot','Command','CommandNot','CommandContains','CommandContainsNot','CommandContainsRegex','CommandContainsRegexNot','CommandOutput','CommandOutputNot','UserExists','UserExistsNot','UserInGroup','UserInGroupNot','PasswordChanged','PasswordChangedNot','ProgramInstalled','ProgramInstalledNot','ProgramVersion','ProgramVersionNot','ServiceUp','ServiceUpNot','FirewallUp','FirewallUpNot','FirewallDefaultBehavior','FirewallDefaultBehaviorNot','GuestDisabledLDM','GuestDisabledLDMNot','PermissionIs','PermissionIsNot','FileOwner','FileOwnerNot','AutoCheckUpdatesEnabled','AutoCheckUpdatesEnabledNot','SecurityPolicy','SecurityPolicyNot','RegistryKey','RegistryKeyNot','RegistryKeyExists','RegistryKeyExistsNot','ServiceStartup','ServiceStartupNot','ScheduledTaskExists','ScheduledTaskExistsNot','ShareExists','ShareExistsNot','UserDetail','UserDetailNot','UserRights','UserRightsNot','WindowsFeature','WindowsFeatureNot','BitlockerEnabled','BitlockerEnabledNot','KernelVersion','KernelVersionNot'];
const statuses=['Not set up','In progress','Set up','Fully tested','Needs review','Intentionally disabled'];

async function api(path,options={}){options.headers={...apiHeaders,...(options.headers||{})};const response=await fetch(path,options);const type=response.headers.get('content-type')||'';const body=type.includes('json')?await response.json():await response.text();if(!response.ok){const error=new Error(body.error||`Request failed (${response.status})`);error.status=response.status;error.body=body;throw error}return body}
function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2400)}
async function downloadPath(path){const kinds={'/api/project/download':'project','/api/config/download':'config','/api/readme/download':'readme','/api/scoring-data':'scoringData'};if(kinds[path]){try{const result=await api('/api/save',{method:'POST',body:JSON.stringify({kind:kinds[path]})});if(!result.cancelled)toast('Saved successfully')}catch(error){alert(error.message)}return}const link=document.createElement('a');link.href=path+(path.includes('?')?'&':'?')+'token='+encodeURIComponent(boot.token);link.download='';document.body.appendChild(link);link.click();link.remove()}
function idFor(check,index){return check.id||`check-${index+1}`}

async function load(){const state=await api('/api/state');project=state.project;issues=state.issues||[];targetDir=state.targetDir;normalize();bindStatic();renderAll()}
function normalize(){
  project=project||{};
  project.config=project.config||{};
  project.config.checks=Array.isArray(project.config.checks)?project.config.checks:[];
  project.config.checks.forEach(check=>{check.pass=Array.isArray(check.pass)?check.pass:[];check.passOverride=Array.isArray(check.passOverride)?check.passOverride:[];check.fail=Array.isArray(check.fail)?check.fail:[]});
  project.forensics=Array.isArray(project.forensics)?project.forensics:[];
  project.forensics.forEach(question=>{question.parts=Array.isArray(question.parts)?question.parts:[];question.parts.forEach(part=>part.answers=Array.isArray(part.answers)?part.answers:[])});
  project.users=Array.isArray(project.users)?project.users:[];
  project.users.forEach(user=>user.groups=Array.isArray(user.groups)?user.groups:[]);
  project.scripts=Array.isArray(project.scripts)?project.scripts:[];
  project.progress=project.progress||{};project.readme=project.readme||{html:''};project.audio=project.audio||{gainName:'',gainData:'',lossName:'',lossData:''};
}

function bindStatic(){
  $('#edition').textContent=`${boot.mode} edition`;$('#modeBadge').textContent=`${boot.mode} studio`;$('#version').textContent=boot.version;
  if(boot.mode!=='development')$$('.dev-only').forEach(n=>n.remove());
  $$('.nav').forEach(button=>button.onclick=()=>showPage(button.dataset.page));
  $('#newProject').onclick=newProject;$('#saveProject').onclick=()=>save(true);$('#downloadProject').onclick=()=>downloadPath('/api/project/download');
  $('#projectImport').onchange=e=>importProject(e.target.files[0]);$('#configImport').onchange=e=>importConfig(e.target.files[0]);
  $('#downloadConfig').onclick=()=>downloadPath('/api/config/download');$('#downloadReadme').onclick=()=>downloadPath('/api/readme/download');
  $('#downloadScoringData').onclick=async()=>{await save(false);if(issues.some(issue=>issue.level==='error')){alert('Fix configuration errors before generating scoring.dat.');return}downloadPath('/api/scoring-data')};
  $('#projectName').oninput=e=>{project.name=e.target.value;dirty()};$('#refreshValidation').onclick=()=>save(true);
  $$('[data-config]').forEach(input=>input.oninput=()=>{const key=input.dataset.config;project.config[key]=input.type==='checkbox'?input.checked:input.value;dirty();renderOverview()});
  $('#revealPassword').onclick=()=>{const input=$('[data-config=password]');input.type=input.type==='password'?'text':'password';$('#revealPassword').textContent=input.type==='password'?'Show':'Hide'};
  $('#addCheck').onclick=()=>$('#checkTemplateDialog').showModal();$('[data-close-template]').onclick=()=>$('#checkTemplateDialog').close();$$('[data-check-template]').forEach(button=>button.onclick=()=>addCheckFromTemplate(button.dataset.checkTemplate));
  $('#copyToml').onclick=()=>navigator.clipboard.writeText($('#tomlPreview').value).then(()=>toast('Configuration copied'));
  ['#regexMode','#regexKey','#regexSeparator','#regexValues','#regexOperator','#regexNumber','#regexMaximum','#regexCase','#regexWhitespace','#regexUnderscore','#regexWhole'].forEach(selector=>{const input=$(selector);input.oninput=input.onchange=()=>{toggleRegexFields();queueRegex()}});
  $$('.recipe').forEach(button=>button.onclick=()=>{$('#regexMode').value=button.dataset.regexMode;toggleRegexFields();queueRegex()});
  $('#copyRegex').onclick=()=>navigator.clipboard.writeText($('#regexOutput').textContent).then(()=>toast('Pattern copied'));$('#regexSamples').oninput=testRegex;
  $$('.format-toolbar [data-command]').forEach(button=>button.onclick=()=>{document.execCommand(button.dataset.command,false,button.dataset.value||null);syncReadme()});
  $('#insertLink').onclick=()=>{const url=prompt('Link address');if(url){document.execCommand('createLink',false,url);syncReadme()}};
  $('#insertTable').onclick=()=>{document.execCommand('insertHTML',false,'<table border="1"><tbody><tr><th>Heading</th><th>Heading</th></tr><tr><td>Value</td><td>Value</td></tr></tbody></table><p><br></p>');syncReadme()};
  $('#restoreReadme').onclick=()=>{$('#readmeEditor').innerHTML='<h2>Critical Services</h2><ul><li>Add critical services here</li></ul><h2>Authorized Users</h2><p>Add authorized users here.</p>';syncReadme()};$('#readmeEditor').oninput=syncReadme;
  $('#addFQ').onclick=()=>{project.forensics.push({number:project.forensics.length+1,title:`Forensic Question ${project.forensics.length+1}`,intro:'',parts:[{prompt:'',answers:[''],caseSensitive:false,flexibleWhitespace:true}]});renderFQs();dirty()};$('#refreshFQs').onclick=renderFQPreview;
  $('#addUser').onclick=()=>{project.users.push({username:'',fullName:'',role:'user',password:'',shell:'/bin/bash',groups:[],addToReadme:true,removalPenalty:false,passwordCheck:false});renderUsers();dirty()};
  $('#usersCSV').onchange=e=>importUsersCSV(e.target.files[0]);$('#generatePasswords').onclick=generateMissingPasswords;$('#downloadCredentials').onclick=downloadCredentials;
  $('#generateScripts').onclick=generateScripts;
  if(boot.mode==='development'){
    $('#targetDir').value=targetDir;$('#targetDir').oninput=e=>targetDir=e.target.value;
    $('#initializeImage').onclick=initializeImage;$('#installProject').onclick=installProject;$('#evaluateNow').onclick=evaluate;
    $('#gainAudio').onchange=e=>loadAudio(e.target.files[0],'gain');$('#lossAudio').onchange=e=>loadAudio(e.target.files[0],'loss');
    $('#autoRefresh').onchange=configureAutoRefresh;$('#implementationSearch').oninput=renderImplementation;$('#releaseImage').onclick=releaseImage;
  }
}

function showPage(name){$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===name));$$('.page').forEach(n=>n.classList.toggle('active',n.id===`page-${name}`));if(name==='config')updateToml();if(name==='forensics')renderFQPreview();if(name==='implementation')renderImplementation()}
function blankCondition(){return{type:'PathExists',path:'',cmd:'',user:'',group:'',name:'',key:'',value:'',after:'',hint:''}}
function addCheckFromTemplate(template){const presets={file:{type:'FileContainsRegex'},path:{type:'PathExistsNot'},command:{type:'Command'},user:{type:'UserExistsNot'},service:{type:'ServiceUp'},custom:{type:'PathExists'}};project.config.checks.push({id:`check-${Date.now()}`,category:'General',message:'New vulnerability',hint:'',points:1,pass:[{...blankCondition(),...(presets[template]||presets.custom)}],passOverride:[],fail:[]});$('#checkTemplateDialog').close();renderChecks();const card=$(`[data-check="${project.config.checks.length-1}"]`);if(card)card.classList.add('open');dirty()}
function dirty(){ $('#saveState').textContent='Unsaved changes';clearTimeout(saveTimer);saveTimer=setTimeout(()=>save(false),700)}
async function save(notify=false){collectOpenEditors();project.updatedAt=new Date().toISOString();const result=await api('/api/project',{method:'PUT',body:JSON.stringify(project)});project=result.project||project;issues=result.issues||[];normalize();$('#saveState').textContent='Saved';renderOverview();updateToml();if(notify)toast('Project saved and validated')}
async function newProject(){if(!confirm('Start a new project? Export the current project first if you need to keep it.'))return;const result=await api('/api/project/new',{method:'POST',body:'{}'});project=result.project;issues=result.issues||[];normalize();renderAll();toast('New project created')}
function collectOpenEditors(){syncReadme(false)}

function renderAll(){
  $('#projectName').value=project.name||'';$$('[data-config]').forEach(input=>{const value=project.config[input.dataset.config];if(input.type==='checkbox')input.checked=!!value;else input.value=value??''});
  project.readme.html=safeHtml(project.readme.html||'');$('#readmeEditor').innerHTML=project.readme.html;syncReadme(false);renderOverview();renderChecks();renderFQs();renderUsers();renderScripts();if(boot.mode==='development')renderImplementation();toggleRegexFields();queueRegex();updateToml();
}
function renderOverview(){
  $('#overviewTitle').textContent=project.name||project.config.title||'Untitled Aeacus Image';$('#metricChecks').textContent=project.config.checks.length;$('#metricPoints').textContent=project.config.checks.filter(c=>+c.points>0).reduce((a,c)=>a+(+c.points||0),0);$('#metricFQs').textContent=project.forensics.length;
  const errors=issues.filter(i=>i.level==='error').length;$('#metricValidation').textContent=errors?`${errors} errors`:'Ready';$('#metricValidation').style.color=errors?'var(--red)':'var(--green)';
  $('#issues').innerHTML=issues.length?issues.map(i=>`<div class="issue ${esc(i.level)}"><b>${esc(i.message)}</b><small>${esc(i.path)}</small></div>`).join(''):'<div class="issue ok"><b>No validation problems found</b><small>The project is structurally ready.</small></div>';
}

function renderChecks(){
  $('#checkSummary').textContent=`${project.config.checks.length} checks`;
  $('#checkList').innerHTML=project.config.checks.map((check,index)=>`<article class="check-card" data-check="${index}"><div class="check-header"><span class="check-number">${index+1}</span><div><strong>${esc(check.message||'Unnamed vulnerability')}</strong><small>${esc(check.category||'General')} · ${esc(check.id||'ID generated on save')}</small></div><span class="points-pill">${+check.points||0} pts</span><button class="icon-button delete-check" title="Delete">×</button></div><div class="check-body"><div class="form-grid"><label class="wide">Message<input data-field="message" value="${esc(check.message)}"></label><label>Category<input data-field="category" value="${esc(check.category||'General')}"></label><label>Points<input type="number" data-field="points" value="${+check.points||0}"></label><label class="wide">Hint<input data-field="hint" value="${esc(check.hint)}"></label></div>${conditionGroup(index,'pass','All pass conditions (AND)',check.pass)}${conditionGroup(index,'passOverride','Alternative pass conditions (OR)',check.passOverride)}${conditionGroup(index,'fail','Failure conditions',check.fail)}<div style="margin-top:14px"><button class="button subtle duplicate-check">Duplicate</button></div></div></article>`).join('');
  $$('.check-card').forEach(card=>bindCheckCard(card,+card.dataset.check));
}
function conditionGroup(checkIndex,key,title,conditions=[]){const list=Array.isArray(conditions)?conditions:[];return`<div class="condition-section" data-group="${key}"><div class="condition-title"><span>${title}</span><button class="text-button add-condition">Add condition</button></div><div>${list.map((condition,index)=>conditionRow(condition,index)).join('')}</div></div>`}
function fieldsForCondition(type){
  const base=type.replace(/Not$/,'').replace(/Regex$/,'');
  if(['FileContains','DirContains','FileEquals'].includes(base))return[['path','File or directory path'],['value',type.includes('Regex')?'Regular expression':'Required content']];
  if(base==='PathExists')return[['path','Path']];
  if(base==='Command')return[['cmd','Command that should '+(type.endsWith('Not')?'fail':'succeed')]];
  if(['CommandContains','CommandOutput'].includes(base))return[['cmd','Command'],['value',type.includes('Regex')?'Expected output pattern':'Expected output']];
  if(['UserExists','PasswordChanged'].includes(base))return[['user','Username'],...(base==='PasswordChanged'?[['value','Original password hash']]:[])];
  if(base==='UserInGroup')return[['user','Username'],['group','Group']];
  if(['ProgramInstalled','ProgramVersion','ServiceUp','ServiceStartup','ScheduledTaskExists','ShareExists','WindowsFeature'].includes(base))return[['name','Name'],...(base==='ProgramVersion'?[['value','Version']]:[])];
  if(base==='PermissionIs')return[['path','Path'],['value','Permission pattern']];
  if(base==='FirewallDefaultBehavior')return[['name','Firewall profile'],['key','Direction (inbound or outbound)'],['value','Behavior (allow or block)']];
  if(base==='FileOwner')return[['path','Path'],['name','Expected owner']];
  if(['SecurityPolicy','RegistryKey'].includes(base))return[['key','Policy or registry key'],['value','Expected value']];
  if(base==='RegistryKeyExists')return[['key','Registry key']];
  if(base==='UserDetail')return[['user','Username'],['key','Detail'],['value','Expected value']];
  if(base==='UserRights')return[['user','Username'],['value','Required right']];
  return[];
}
function conditionRow(condition,index){const available=conditionTypes.includes(condition.type)?conditionTypes:[condition.type,...conditionTypes];const options=available.map(type=>`<option ${type===condition.type?'selected':''}>${type.replace(/([a-z])([A-Z])/g,'$1 $2')}</option>`).join('');const fields=fieldsForCondition(condition.type).map(([field,label])=>`<label><span>${esc(label)}</span><input data-cond="${field}" value="${esc(condition[field])}"></label>`).join('');return`<div class="condition" data-condition="${index}"><label class="condition-type"><span>Check type</span><select data-cond="type">${options}</select></label>${fields}<button class="icon-button remove-condition" title="Remove condition">×</button></div>`}
function bindCheckCard(card,index){
  $('.check-header',card).onclick=e=>{if(!e.target.closest('button'))card.classList.toggle('open')};
  $('.delete-check',card).onclick=()=>{if(confirm('Delete this vulnerability?')){project.config.checks.splice(index,1);renderChecks();dirty()}};
  $$('[data-field]',card).forEach(input=>input.oninput=()=>{let value=input.value;if(input.dataset.field==='points')value=+value;project.config.checks[index][input.dataset.field]=value;renderOverview();dirty()});
  $$('.condition-section',card).forEach(section=>{const key=section.dataset.group;$('.add-condition',section).onclick=()=>{project.config.checks[index][key].push(blankCondition());renderChecks();document.querySelector(`[data-check="${index}"]`).classList.add('open');dirty()};$$('.condition',section).forEach(row=>{const conditionIndex=+row.dataset.condition;$$('[data-cond]',row).forEach(input=>input.oninput=()=>{project.config.checks[index][key][conditionIndex][input.dataset.cond]=input.value;if(input.dataset.cond==='type'){renderChecks();document.querySelector(`[data-check="${index}"]`).classList.add('open')}dirty()});$('.remove-condition',row).onclick=()=>{project.config.checks[index][key].splice(conditionIndex,1);renderChecks();document.querySelector(`[data-check="${index}"]`).classList.add('open');dirty()}})});
  $('.duplicate-check',card).onclick=()=>{const copy=JSON.parse(JSON.stringify(project.config.checks[index]));copy.id=`${copy.id||'check'}-copy-${Date.now()}`;project.config.checks.splice(index+1,0,copy);renderChecks();dirty()};
}
async function updateToml(){if(!project)return;try{const response=await fetch('/api/config/download',{headers:{'X-Aeacus-Token':boot.token}});$('#tomlPreview').value=await response.text()}catch(error){$('#tomlPreview').value=`Unable to render: ${error.message}`}}

function toggleRegexFields(){const mode=$('#regexMode').value,numeric=mode==='integer';$$('.numeric-field').forEach(n=>n.classList.toggle('hidden',!numeric));$$('.regex-key,.regex-values').forEach(n=>n.classList.toggle('hidden',numeric));$$('.recipe').forEach(button=>button.classList.toggle('active',button.dataset.regexMode===mode))}
let regexTimer;function queueRegex(){clearTimeout(regexTimer);regexTimer=setTimeout(generateRegex,100)}
async function generateRegex(){const request={mode:$('#regexMode').value,key:$('#regexKey').value,separator:$('#regexSeparator').value,values:$('#regexValues').value.split('\n').map(v=>v.trim()).filter(Boolean),caseSensitive:$('#regexCase').checked,flexibleWhitespace:$('#regexWhitespace').checked,spacesUnderscoresSame:$('#regexUnderscore').checked,wholeLine:$('#regexWhole').checked,operator:$('#regexOperator').value,number:+$('#regexNumber').value,maximum:+$('#regexMaximum').value};try{const result=await api('/api/regex',{method:'POST',body:JSON.stringify(request)});$('#regexOutput').textContent=result.pattern;$('#numericTests').innerHTML=(result.tests||[]).map(t=>`<div>${esc(t)}</div>`).join('');testRegex()}catch(error){$('#regexOutput').textContent=error.message;$('#regexMatches').innerHTML=''}}
function testRegex(){let pattern=$('#regexOutput').textContent,flags='';if(pattern.startsWith('(?i)')){pattern=pattern.slice(4);flags='i'}pattern=pattern.replaceAll('[[:space:]]','\\s').replaceAll('[_[:space:]]','[_\\s]');let regex;try{regex=new RegExp(pattern,flags)}catch{return}$('#regexMatches').innerHTML=$('#regexSamples').value.split('\n').filter(Boolean).map(line=>{const match=regex.test(line);return`<div class="match-line ${match?'match':''}">${match?'✓':'✗'} ${esc(line)}</div>`}).join('')}

function releasedReadmeMarkup(){const os=esc(project.config.os||'Operating System'),title=esc(project.config.title||'Aeacus Image');return`<article class="released-readme-page"><p class="released-logo"><img src="/logo.png" alt="Aeacus"></p><h1><b>${os} ${title} README</b></h1><p>Please read the entire README thoroughly before modifying anything on this computer.</p><h2>Unique Identifier</h2><p>If you have not yet entered a valid Team ID, please do so immediately by double clicking the “Team ID” icon on the desktop.</p><h2>Forensics Questions</h2><p>Valid scored forensic questions are located directly on the Desktop. Read them before modifying the computer.</p><h2>Competition Scenario</h2><p>This is a critical computer in a production environment. Use only authorized accounts and approved software.</p><h2><b>${os}</b></h2>${safeHtml(project.readme.html)}<h2>Competition Guidelines</h2><ul><li>Do not disable or stop the CSSClient service or process.</li><li>Do not remove authorized users or their home directories.</li><li>Use the Scoring Report desktop icon to view current scoring.</li></ul><p class="released-footer">The Aeacus Project is not affiliated with or endorsed by the Air Force Association or the University of Texas at San Antonio.</p></article>`}
function syncReadme(mark=true){if(!project)return;project.readme.html=safeHtml($('#readmeEditor').innerHTML);$('#readmePreview').innerHTML=releasedReadmeMarkup();if(mark)dirty()}

function renderFQs(){
  $('#fqList').innerHTML=project.forensics.map((question,q)=>`<article class="fq-card" data-fq="${q}"><div class="panel-heading"><h2>FQ${q+1}</h2><button class="text-button danger-text remove-fq">Delete</button></div><div class="form-grid"><label>Title<input data-fqfield="title" value="${esc(question.title)}"></label><label class="wide">Introduction<textarea data-fqfield="intro">${esc(question.intro)}</textarea></label></div><div class="fq-parts">${(question.parts||[]).map((part,p)=>`<div class="fq-part" data-part="${p}"><label>Question<textarea data-partfield="prompt">${esc(part.prompt)}</textarea></label><label>Accepted answers<textarea data-partfield="answers" placeholder="One per line">${esc((part.answers||[]).join('\n'))}</textarea></label><div><label class="check-label"><input type="checkbox" data-partfield="caseSensitive" ${part.caseSensitive?'checked':''}> Case sensitive</label><label class="check-label"><input type="checkbox" data-partfield="flexibleWhitespace" ${part.flexibleWhitespace?'checked':''}> Flexible whitespace</label><button class="text-button danger-text remove-part">Remove</button></div></div>`).join('')}</div><button class="button subtle add-part">Add part</button></article>`).join('');
  $$('.fq-card').forEach(card=>bindFQ(card,+card.dataset.fq));renderFQPreview();
}
function bindFQ(card,q){$$('[data-fqfield]',card).forEach(input=>input.oninput=()=>{project.forensics[q][input.dataset.fqfield]=input.value;dirty();renderFQPreview()});$$('.fq-part',card).forEach(row=>{const p=+row.dataset.part;$$('[data-partfield]',row).forEach(input=>input.oninput=()=>{const field=input.dataset.partfield;project.forensics[q].parts[p][field]=input.type==='checkbox'?input.checked:field==='answers'?input.value.split('\n').map(v=>v.trim()).filter(Boolean):input.value;dirty();renderFQPreview()});$('.remove-part',row).onclick=()=>{project.forensics[q].parts.splice(p,1);renderFQs();dirty()}});$('.add-part',card).onclick=()=>{project.forensics[q].parts.push({prompt:'',answers:[''],caseSensitive:false,flexibleWhitespace:true});renderFQs();dirty()};$('.remove-fq',card).onclick=()=>{project.forensics.splice(q,1);renderFQs();dirty()}}
async function renderFQPreview(){if(!project)return;try{await api('/api/project',{method:'PUT',body:JSON.stringify(project)});const files=await api('/api/forensics/download');$('#fqPreview').innerHTML=Object.entries(files).map(([name,content])=>`<div class="file-preview"><b>${esc(name)}</b><pre>${esc(content)}</pre></div>`).join('')||'<span>No questions yet.</span>'}catch(error){console.error(error)}}

function renderUsers(){
  $('#userList').innerHTML=project.users.map((user,index)=>`<article class="user-card" data-user="${index}"><div class="panel-heading"><h2>${esc(user.username||'New user')}</h2><button class="text-button danger-text remove-user">Delete</button></div><div class="user-grid"><label>Username<input data-userfield="username" value="${esc(user.username)}"></label><label>Full name<input data-userfield="fullName" value="${esc(user.fullName)}"></label><label>Role<select data-userfield="role"><option value="user" ${user.role==='user'?'selected':''}>User</option><option value="admin" ${user.role==='admin'?'selected':''}>Administrator</option><option value="primary" ${user.role==='primary'?'selected':''}>Primary administrator</option></select></label><label>Initial password<input type="password" data-userfield="password" value="${esc(user.password)}"></label><label>Linux shell<input data-userfield="shell" value="${esc(user.shell||'/bin/bash')}"></label><label>Additional groups<input data-userfield="groups" value="${esc((user.groups||[]).join(', '))}"></label></div><div class="user-options"><label class="check-label"><input type="checkbox" data-userfield="addToReadme" ${user.addToReadme?'checked':''}> Add to README</label><label class="check-label"><input type="checkbox" data-userfield="removalPenalty" ${user.removalPenalty?'checked':''}> Generate removal penalty</label><label class="check-label"><input type="checkbox" data-userfield="passwordCheck" ${user.passwordCheck?'checked':''}> Generate password check</label><label class="check-label"><input type="checkbox" data-userfield="groupChecks" ${user.groupChecks?'checked':''}> Generate group checks</label></div></article>`).join('');
  $$('.user-card').forEach(card=>{const index=+card.dataset.user;$$('[data-userfield]',card).forEach(input=>input.oninput=()=>{const field=input.dataset.userfield;project.users[index][field]=input.type==='checkbox'?input.checked:field==='groups'?input.value.split(',').map(v=>v.trim()).filter(Boolean):input.value;dirty()});$('.remove-user',card).onclick=()=>{project.users.splice(index,1);renderUsers();dirty()}})
}
function parseCSVLine(line){const values=[];let value='',quoted=false;for(let index=0;index<line.length;index++){const char=line[index];if(char==='"'){if(quoted&&line[index+1]==='"'){value+='"';index++}else quoted=!quoted}else if(char===','&&!quoted){values.push(value.trim());value=''}else value+=char}values.push(value.trim());return values}
async function importUsersCSV(file){if(!file)return;const lines=(await file.text()).split(/\r?\n/).filter(line=>line.trim());if(lines.length<2){alert('The CSV needs a header row and at least one user.');return}const headers=parseCSVLine(lines.shift()).map(value=>value.toLowerCase().replace(/[^a-z]/g,''));let added=0;for(const line of lines){const values=parseCSVLine(line),row={};headers.forEach((header,index)=>row[header]=values[index]||'');const username=row.username||row.user;if(!username)continue;const requested=(row.role||'user').toLowerCase();project.users.push({username,fullName:row.fullname||row.name||'',role:['admin','primary'].includes(requested)?requested:'user',password:row.password||'',shell:row.shell||'/bin/bash',groups:(row.groups||'').split(/[|;]/).map(value=>value.trim()).filter(Boolean),addToReadme:true,removalPenalty:false,passwordCheck:false,groupChecks:false});added++}renderUsers();dirty();toast(`${added} users imported`)}
function randomPassword(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%';const bytes=new Uint32Array(18);crypto.getRandomValues(bytes);return [...bytes].map(v=>chars[v%chars.length]).join('')}
function generateMissingPasswords(){let count=0;project.users.forEach(user=>{if(!user.password){user.password=randomPassword();count++}});renderUsers();dirty();toast(`${count} passwords generated`)}
function downloadCredentials(){const rows=['Username,Role,Initial Password',...project.users.map(user=>[user.username,user.role,user.password].map(value=>'"'+String(value||'').replaceAll('"','""')+'"').join(','))];const blob=new Blob([rows.join('\n')+'\n'],{type:'text/csv'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=(project.config.name||'aeacus')+'-author-credentials.csv';link.click();URL.revokeObjectURL(link.href)}
async function generateScripts(){await save(false);project.scripts=await api('/api/scripts/generate',{method:'POST',body:'{}'});renderScripts();dirty();toast('Windows and Linux scripts generated')}
function renderScripts(){$('#scriptList').innerHTML=(project.scripts||[]).map(script=>`<article class="script-card"><div class="panel-heading"><h3>${esc(script.name)}</h3><span>${esc(script.platform)}</span></div><pre>${esc(script.content)}</pre>${boot.mode==='development'?`<button class="button danger run-script" data-name="${esc(script.name)}">Review and run</button>`:''}</article>`).join('')||'<span>Generate scripts after adding users.</span>';$$('.run-script').forEach(button=>button.onclick=()=>confirmRunScript(button.dataset.name))}
async function confirmRunScript(name){if(!confirm(`Run “${name}” as an elevated setup script on this image? Review every command first.`))return;try{const result=await api('/api/development/run-script',{method:'POST',body:JSON.stringify({name})});toast('Script finished');alert(result.output||'Script completed')}catch(error){alert(error.message)}}

async function importProject(file){if(!file)return;try{const data=JSON.parse(await file.text());const result=await api('/api/project/import',{method:'POST',body:JSON.stringify(data)});project=result.project;issues=result.issues;normalize();renderAll();toast('Project imported')}catch(error){alert(`Could not import project: ${error.message}`)}}
async function importConfig(file){if(!file)return;try{const result=await api('/api/config/import',{method:'POST',body:JSON.stringify({content:await file.text()})});project=result.project;issues=result.issues;normalize();renderAll();toast('scoring.conf imported')}catch(error){alert(`Could not import config: ${error.message}`)}}

function renderImplementation(){if(boot.mode!=='development')return;$('#gainAudioName').textContent=project.audio.gainName||'Default gain.wav';$('#lossAudioName').textContent=project.audio.lossName||'Default alarm.wav';const query=($('#implementationSearch')?.value||'').trim().toLowerCase();const tested=project.config.checks.filter((check,index)=>{const progress=project.progress[idFor(check,index)]||{};return progress.seenPassing&&progress.seenFailing}).length;$('#testCoverage').textContent=project.config.checks.length?Math.round(tested/project.config.checks.length*100)+'%':'0%';const rows=project.config.checks.map((check,index)=>({check,index,progress:project.progress[idFor(check,index)]||{}})).filter(item=>!query||`${item.check.message} ${item.check.category} ${item.check.id}`.toLowerCase().includes(query)).map(({check,index,progress})=>{const live=evaluationByIndex[index+1]||progress.lastResult||'not evaluated';return`<div class="implementation-row"><span class="check-number">${index+1}</span><div><strong>${esc(check.message)}</strong><small>${esc(check.category||'General')} · ${check.points} pts</small></div><span class="result ${esc(live)}">${esc(live)}</span><select data-progress="${esc(idFor(check,index))}">${statuses.map(status=>`<option ${progress.status===status?'selected':''}>${status}</option>`).join('')}</select><span class="observation-state ${progress.seenPassing&&progress.seenFailing?'complete':''}">${progress.seenPassing?'Pass ✓':'Pass —'} · ${progress.seenFailing?'Fail ✓':'Fail —'}</span></div>`}).join('');$('#implementationList').innerHTML=rows||'<div class="panel">No matching vulnerabilities.</div>';$$('[data-progress]').forEach(select=>select.onchange=()=>{const id=select.dataset.progress;project.progress[id]=project.progress[id]||{};project.progress[id].status=select.value;dirty()})}
function loadAudio(file,kind){if(!file)return;if(file.size>5*1024*1024){alert('Sound files must be 5 MiB or smaller.');return}const reader=new FileReader();reader.onload=()=>{project.audio=project.audio||{};project.audio[`${kind}Name`]=file.name;project.audio[`${kind}Data`]=reader.result;$(`#${kind}AudioName`).textContent=file.name;dirty()};reader.readAsDataURL(file)}
async function initializeImage(){if(!confirm(`Initialize Aeacus files in ${targetDir}? Existing unrelated files will not be removed.`))return;try{const result=await api('/api/development/initialize',{method:'POST',body:JSON.stringify({target:targetDir})});$('#devMessage').textContent=`Initialized: ${result.copied.join(', ')||'directory created'}`;toast('Image initialized')}catch(error){alert(error.message)}}
async function installProject(){if(!confirm(`Install the current scoring.conf, README, scripts, sounds, and forensic files into ${targetDir}?`))return;try{await save(false);const result=await api('/api/development/install',{method:'POST',body:'{}'});$('#devMessage').textContent=result.message;toast('Project installed on image')}catch(error){alert(error.message)}}
async function evaluate(){try{const result=await api('/api/development/evaluate',{method:'POST',body:'{}'});const evaluation=result.evaluation;evaluationByIndex={};evaluation.results.forEach(item=>evaluationByIndex[item.index]=item.status);project.progress=result.progress;$('#liveScore').textContent=evaluation.score;$('#livePassing').textContent=evaluation.results.filter(r=>r.status==='passing').length;$('#liveFailing').textContent=evaluation.results.filter(r=>r.status==='failing').length;renderImplementation();dirty()}catch(error){$('#devMessage').textContent=error.message}}
let refreshTimer;function configureAutoRefresh(){clearInterval(refreshTimer);const seconds=+$('#autoRefresh').value;if(seconds)refreshTimer=setInterval(evaluate,seconds*1000)}
async function releaseImage(confirmUntested=false){if(!confirm('Release permanently removes Development Studio and plaintext author files. Continue to validation?'))return;$('#releaseOutput').textContent='Validating and releasing…';try{await save(false);const result=await api('/api/development/release',{method:'POST',body:JSON.stringify({confirmUntested,confirmCleanup:$('#cleanupConfirm').checked})});$('#releaseOutput').textContent=result.output+'\n'+result.message;alert(result.message)}catch(error){if(error.status===409&&error.body.untested){const names=error.body.untested;const proceed=confirm(`${names.length} vulnerabilities are not fully tested:\n\n${names.join('\n')}\n\nRelease anyway?`);if(proceed)return releaseImage(true)}$('#releaseOutput').textContent=(error.body&&error.body.output)||error.message;alert(error.message)}}

load().catch(error=>{console.error(error);document.body.innerHTML=`<pre style="padding:30px;color:white">Studio failed to start: ${esc(error.message)}</pre>`});
