name: Core Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Test core runtime
        run: go test .

      - name: Cross-compile Aeacus and Phocus
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /tmp/aeacus-linux .
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags phocus -o /tmp/phocus-linux .
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o /tmp/aeacus-windows.exe .
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -tags phocus -o /tmp/phocus-windows.exe .
